use serde::{Deserialize, Serialize};

use crate::actions::ActionType;
use crate::dsl::DslStep;

/// A node in the Element-Transition Graph — represents a unique screen state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EtgNode {
    pub id: u64,
    pub package_name: String,
    pub activity_name: String,
    pub state_hash: u64,
    pub interactive_elements: Vec<String>,
    pub visit_count: u32,
    pub last_visit_ms: u64,
}

/// An edge in the Element-Transition Graph — represents an action between states.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EtgEdge {
    pub from_node: u64,
    pub to_node: u64,
    pub action: ActionType,
    pub success_count: u32,
    pub fail_count: u32,
    pub avg_duration_ms: u32,
    pub last_used_ms: u64,
}

impl EtgEdge {
    /// Reliability ratio: successes / total attempts. Returns 0.0 if no attempts.
    #[must_use]
    pub fn reliability(&self) -> f32 {
        let total = self.success_count + self.fail_count;
        if total == 0 {
            return 0.0;
        }
        self.success_count as f32 / total as f32
    }

    /// Reliability with temporal freshness decay.
    /// Applies a 14-day half-life: `effective = raw × 2^(−days_since_use / 14.0)`.
    /// Stale edges that haven't been tested recently get reduced scores.
    /// See: AURA-V4-BATCH3-FOUNDATION-AUDIT §1.5 — "reliability() has no temporal decay".
    #[must_use]
    pub fn effective_reliability(&self, now_ms: u64) -> f32 {
        let raw = self.reliability();
        if raw == 0.0 || self.last_used_ms == 0 {
            return raw;
        }
        let elapsed_ms = now_ms.saturating_sub(self.last_used_ms);
        let days = elapsed_ms as f64 / 86_400_000.0;
        let freshness = 2.0_f64.powf(-days / 14.0) as f32;
        raw * freshness
    }
}

/// A path through the ETG — sequence of nodes and edges with aggregate metrics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EtgPath {
    pub nodes: Vec<u64>,
    pub edges: Vec<u64>,
    pub total_reliability: f32,
    pub estimated_duration_ms: u32,
}

/// An action plan — either generated by ETG lookup, LLM, or hybrid approach.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActionPlan {
    pub goal_description: String,
    pub steps: Vec<DslStep>,
    pub estimated_duration_ms: u32,
    pub confidence: f32,
    pub source: PlanSource,
}

/// How the action plan was generated.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum PlanSource {
    /// Found a known path in the ETG.
    EtgLookup,
    /// Generated entirely by the LLM.
    LlmGenerated,
    /// ETG provided partial path, LLM filled gaps.
    Hybrid,
    /// User manually defined the steps.
    UserDefined,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_etg_edge_reliability() {
        let edge = EtgEdge {
            from_node: 1,
            to_node: 2,
            action: ActionType::Tap { x: 100, y: 200 },
            success_count: 9,
            fail_count: 1,
            avg_duration_ms: 200,
            last_used_ms: 1_700_000_000_000,
        };
        assert!((edge.reliability() - 0.9).abs() < f32::EPSILON);
    }

    #[test]
    fn test_etg_edge_reliability_zero_attempts() {
        let edge = EtgEdge {
            from_node: 1,
            to_node: 2,
            action: ActionType::Back,
            success_count: 0,
            fail_count: 0,
            avg_duration_ms: 0,
            last_used_ms: 0,
        };
        assert!((edge.reliability() - 0.0).abs() < f32::EPSILON);
    }

    #[test]
    fn test_action_plan_creation() {
        let plan = ActionPlan {
            goal_description: "Open Settings".to_string(),
            steps: vec![],
            estimated_duration_ms: 5000,
            confidence: 0.85,
            source: PlanSource::EtgLookup,
        };
        assert_eq!(plan.source, PlanSource::EtgLookup);
        assert!(plan.confidence > 0.8);
    }

    #[test]
    fn test_etg_node_creation() {
        let node = EtgNode {
            id: 42,
            package_name: "com.android.settings".to_string(),
            activity_name: ".Settings".to_string(),
            state_hash: 0xDEADBEEF,
            interactive_elements: vec!["WiFi toggle".to_string(), "Bluetooth toggle".to_string()],
            visit_count: 15,
            last_visit_ms: 1_700_000_000_000,
        };
        assert_eq!(node.interactive_elements.len(), 2);
        assert_eq!(node.visit_count, 15);
    }

    #[test]
    fn test_effective_reliability_fresh_edge() {
        let edge = EtgEdge {
            action: "tap".to_string(),
            success_count: 9,
            fail_count: 1,
            avg_duration_ms: 200,
            last_used_ms: 1_000_000,
        };
        // Fresh edge (1ms ago): effective ≈ raw
        let effective = edge.effective_reliability(1_000_001);
        let raw = edge.reliability();
        assert!((effective - raw).abs() < 0.001);
    }

    #[test]
    fn test_effective_reliability_stale_edge() {
        let now_ms: u64 = 1_700_000_000_000;
        let twenty_eight_days_ago = now_ms - (28 * 86_400_000); // 2 half-lives
        let edge = EtgEdge {
            action: "tap".to_string(),
            success_count: 9,
            fail_count: 1,
            avg_duration_ms: 200,
            last_used_ms: twenty_eight_days_ago,
        };
        let raw = edge.reliability(); // 0.9
        let effective = edge.effective_reliability(now_ms);
        // After 28 days (2 × 14-day half-life): effective ≈ raw × 0.25
        assert!(effective < raw * 0.30, "expected decay, got {effective}");
        assert!(effective > raw * 0.20, "too much decay, got {effective}");
    }
}
