#!/usr/bin/env python3
"""
AURA Regression Test Generator

Auto-generates regression test code from the failure taxonomy.
Run this whenever a new failure is added to the taxonomy.

Usage:
    python generate_regression_test.py
    python generate_regression_test.py --all
    python generate_regression_test.py --id F001
"""

import json
import sys
import argparse
from pathlib import Path
from typing import Dict, Any

RUST_TEST_TEMPLATE = """
//! Regression test for {id}: {name}
//!
//! {description}
//!
//! Generated by: generate_regression_test.py
//! DO NOT EDIT MANUALLY — update taxonomy instead

#[cfg(test)]
mod regression_test_{id_lower} {{
    /// Test: {test_name}
    #[test]
    fn test_{test_name_snake}() {{
        {test_code}
    }}
}}
"""


class RegressionTestGenerator:
    """Generates regression tests from taxonomy entries."""

    TEST_TEMPLATES = {
        "F001": {
            "name": "SIGSEGV at startup with NDK r26b",
            "test": """
let cargo_content = std::fs::read_to_string("Cargo.toml").unwrap();
let has_lto_true = cargo_content.contains(r#"lto = "true""#);
let has_panic_abort = cargo_content.contains(r#"panic = "abort""#);

if has_lto_true && has_panic_abort {{
    panic!("F001 DANGER: lto=true + panic=abort causes SIGSEGV on NDK r26b!");
}}

assert!(!has_lto_true || !has_panic_abort, 
    "Cannot have lto=true AND panic=abort together");
            """,
        },
        "F002": {
            "name": "Bionic allocator OOM",
            "test": """
let max_memory_mb = 512;
assert!(max_memory_mb <= 512, "Memory must fit within Android constraints");
            """,
        },
        "F003": {
            "name": "Termux permission denied",
            "test": """
use std::env;
let home = env::var("HOME").expect("HOME must be set on Termux");
assert!(!home.is_empty(), "HOME must not be empty");
            """,
        },
        "F004": {
            "name": "Reflection schema mismatch",
            "test": """
let expected_fields = vec!["safe", "correct", "concerns", "verdict"];
println!("Reflection schema fields: {{:?}}", expected_fields);
            """,
        },
        "F005": {
            "name": "Semantic similarity stub",
            "test": """
println!("Semantic similarity: tested via planner unit tests");
            """,
        },
        "F006": {
            "name": "Ethics audit bypass",
            "test": """
println!("Ethics bypass: tested via ethics unit tests");
            """,
        },
        "F007": {
            "name": "GDPR erasure incomplete",
            "test": """
println!("GDPR erasure: tested via GDPR integration tests");
            """,
        },
    }

    def __init__(self, base_path: Path):
        self.base_path = base_path

    def generate(self, failure_id: str) -> str:
        """Generate regression test for a failure ID."""
        template = self.TEST_TEMPLATES.get(failure_id)
        if not template:
            return f"// No template for {failure_id} — needs manual test"

        test_code = template["test"].strip()
        test_name_snake = (
            template["name"].lower().replace(" ", "_").replace("-", "_")[:50]
        )

        return RUST_TEST_TEMPLATE.format(
            id=failure_id,
            id_lower=failure_id.lower(),
            name=template["name"],
            description=f"Auto-generated regression test for {failure_id}",
            test_name=template["name"].replace(" ", "_").replace("-", "_"),
            test_name_snake=test_name_snake,
            test_code=test_code,
        )

    def generate_all(self) -> Dict[str, str]:
        """Generate all regression tests."""
        results = {}
        for fid in self.TEST_TEMPLATES:
            results[fid] = self.generate(fid)
        return results


def main():
    parser = argparse.ArgumentParser(description="Generate AURA regression tests")
    parser.add_argument("--id", type=str, help="Generate test for specific failure ID")
    parser.add_argument("--all", action="store_true", help="Generate all tests")
    parser.add_argument("--output", type=str, help="Output directory")
    args = parser.parse_args()

    base = Path(args.output) if args.output else Path("infrastructure/tests/regression")
    base.mkdir(parents=True, exist_ok=True)

    gen = RegressionTestGenerator(base)

    if args.id:
        test_code = gen.generate(args.id)
        output_file = base / f"test_{args.id.lower()}.rs"
        output_file.write_text(test_code)
        print(f"Generated: {output_file}")

    elif args.all:
        all_tests = gen.generate_all()
        for fid, code in all_tests.items():
            output_file = base / f"test_{fid.lower()}.rs"
            output_file.write_text(code)
            print(f"Generated: {output_file}")
        print(f"\nGenerated {len(all_tests)} regression tests")

    else:
        parser.print_help()
        print("\nAvailable templates: F001, F002, F003, F004, F005, F006, F007")


if __name__ == "__main__":
    main()
