//! Inference engine for AURA Neocortex.
//!
//! Orchestrates the full 6-layer teacher structure stack:
//!
//! - **Layer 0 (GBNF)**: Grammar-constrained generation via `grammar.rs`
//! - **Layer 1 (CoT)**: Chain-of-thought forcing via `prompts::build_cot_prompt()`
//! - **Layer 2 (Confidence)**: Logprob-based confidence estimation → cascade trigger
//! - **Layer 3 (Cascade Retry)**: Escalate to larger model on low confidence
//! - **Layer 4 (Reflection)**: Cross-model check (Brainstem validates Neocortex)
//! - **Layer 5 (Best-of-N)**: Run N inferences with Mirostat-divergent tau, vote
//!
//! Two generation modes:
//! - **DGS (Document-Guided Scripting)**: Single-pass, template-guided, fast path
//! - **Semantic ReAct**: Iterative Thought→Action→Observation cycles
//!
//! The main entry point is `InferenceEngine::infer()`, which decides the mode
//! and runs the full pipeline including cascade retry and reflection.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::Instant;

use aura_types::actions::{ActionType, ElementAssertion, TargetSelector};
use aura_types::dsl::{DslStep, FailureStrategy};
use aura_types::etg::{ActionPlan, PlanSource};
use aura_types::ipc::{InferenceMode, ModelParams, NeocortexToDaemon};
use tracing::{debug, error, info, trace, warn};

use crate::context::{AssembledPrompt, TokenTracker};
use crate::grammar::ChainOfThoughtOutput;
use crate::model::{self, ModelManager};
use crate::prompts::{self, PromptSlots, ReActStep};
use crate::tool_format::{self, ParsedOutput};

// ─── Constants ──────────────────────────────────────────────────────────────

/// Maximum ReAct iterations before forcing termination.
const MAX_REACT_ITERATIONS: u32 = 5;

/// Number of Best-of-N samples (Layer 5).
const BON_SAMPLES: usize = 3;

/// Maximum cascade retries before giving up (Layer 3).
/// Also enforced by `ModelManager::cascades_exhausted()`.
const MAX_CASCADE_RETRIES: u32 = 3;

/// Confidence threshold below which we attempt cascade escalation.
const CASCADE_CONFIDENCE_THRESHOLD: f32 = 0.5;

/// Confidence threshold below which we flag the output (very low quality).
const LOW_CONFIDENCE_THRESHOLD: f32 = 0.3;

/// Progress reporting: minimum milliseconds between updates.
const PROGRESS_INTERVAL_MS: u64 = 500;

/// Progress reporting: report every N tokens.
const PROGRESS_INTERVAL_TOKENS: u32 = 50;

/// Marker that the ReAct model emits when it has a final answer.
const REACT_DONE_MARKER: &str = "DONE:";

/// Error codes for `NeocortexToDaemon::Error`.
mod error_codes {
    /// Model not loaded.
    pub const MODEL_NOT_LOADED: u16 = 1;
    /// Inference cancelled by caller.
    pub const CANCELLED: u16 = 2;
    /// Token generation failed (FFI error, OOM, etc.).
    pub const GENERATION_FAILED: u16 = 3;
    /// Output parsing failed after all retries.
    pub const PARSE_FAILED: u16 = 4;
    /// Reflection verdict: rejected.
    pub const REFLECTION_REJECTED: u16 = 5;
    /// Cascade exhausted — could not produce confident output.
    pub const CASCADE_EXHAUSTED: u16 = 6;
    /// Token budget fully consumed.
    pub const TOKEN_BUDGET_EXHAUSTED: u16 = 7;
}

// ─── Inference outcome (internal) ───────────────────────────────────────────

/// Result of a single inference pass (before IPC conversion).
#[derive(Debug, Clone)]
struct InferenceOutcome {
    /// Raw text generated by the model.
    raw_output: String,
    /// Parsed output (plan, steps, or reply).
    parsed: Option<ParsedOutput>,
    /// Estimated confidence in the output (0.0–1.0).
    confidence: f32,
    /// Number of tokens generated.
    tokens_generated: u32,
    /// Whether chain-of-thought was active (and the thinking text, if any).
    cot_thinking: Option<String>,
}

/// Result of the raw token generation loop.
#[derive(Debug)]
struct GenerationResult {
    /// Decoded text from generated tokens.
    text: String,
    /// Number of tokens produced.
    token_count: u32,
    /// Whether generation was stopped early by a stop sequence.
    stopped_by_sequence: bool,
    /// Whether cancelled by the caller.
    was_cancelled: bool,
    /// Approximate mean logprob (if available, else None).
    /// On host stubs this is always None.
    mean_logprob: Option<f32>,
}

// ─── ReAct state ────────────────────────────────────────────────────────────

/// Accumulates state across ReAct iterations.
#[derive(Debug, Default)]
struct ReActState {
    /// Completed steps so far.
    steps: Vec<ReActStep>,
    /// Running token count consumed across all iterations.
    total_tokens: u32,
    /// Iteration counter.
    iteration: u32,
}

impl ReActState {
    /// Add a completed step.
    fn push_step(&mut self, step: ReActStep) {
        self.total_tokens += step.estimate_tokens();
        self.steps.push(step);
    }

    /// Whether we have reached the iteration limit.
    fn is_exhausted(&self) -> bool {
        self.iteration >= MAX_REACT_ITERATIONS
    }

    /// Whether the latest step's action text contains the DONE marker.
    fn is_done(&self) -> bool {
        self.steps
            .last()
            .map(|s| s.action.contains(REACT_DONE_MARKER))
            .unwrap_or(false)
    }

    /// Convert accumulated steps into `ReActStep` refs for prompt injection.
    fn as_prompt_history(&self) -> Vec<ReActStep> {
        self.steps.clone()
    }

    /// Extract the final answer from the last step (everything after DONE:).
    fn final_answer(&self) -> Option<String> {
        self.steps.last().and_then(|s| {
            s.action
                .find(REACT_DONE_MARKER)
                .map(|idx| s.action[idx + REACT_DONE_MARKER.len()..].trim().to_string())
        })
    }
}

// ─── Inference engine ───────────────────────────────────────────────────────

/// Callback type for sending progress / result messages back through IPC.
pub type ProgressSender = Box<dyn FnMut(NeocortexToDaemon) + Send>;

/// The core inference engine.
///
/// Orchestrates the full teacher stack pipeline: generation → confidence check
/// → cascade retry → reflection → final output.
pub struct InferenceEngine {
    /// Shared cancellation flag — set to `true` to abort current inference.
    cancel_token: Arc<AtomicBool>,
}

impl InferenceEngine {
    /// Create a new inference engine with a shared cancellation token.
    pub fn new(cancel_token: Arc<AtomicBool>) -> Self {
        Self { cancel_token }
    }

    /// Cancel the currently running inference.
    pub fn cancel(&self) {
        self.cancel_token.store(true, Ordering::SeqCst);
        info!("inference cancellation requested");
    }

    /// Check if cancellation has been requested.
    fn is_cancelled(&self) -> bool {
        self.cancel_token.load(Ordering::SeqCst)
    }

    // ── Main entry point ────────────────────────────────────────────────

    /// Run inference on the assembled prompt.
    ///
    /// This is the main entry point.  It:
    /// 1. Validates the model is loaded
    /// 2. Decides between DGS (single-pass) and Semantic ReAct (iterative)
    /// 3. Runs the appropriate pipeline with cascade retry
    /// 4. Optionally runs reflection (Layer 4) for structured modes
    /// 5. Returns the final IPC response
    ///
    /// `send_progress` is called for intermediate progress updates.
    pub fn infer(
        &self,
        manager: &mut ModelManager,
        prompt: AssembledPrompt,
        mode: InferenceMode,
        send_progress: &mut ProgressSender,
    ) -> NeocortexToDaemon {
        // Reset cancel token for this request.
        self.cancel_token.store(false, Ordering::SeqCst);

        // Ensure model is loaded.
        let is_stub = match manager.loaded_mut() {
            Some(m) => {
                m.last_used = Instant::now();
                m.is_stub()
            }
            None => {
                return NeocortexToDaemon::Error {
                    code: error_codes::MODEL_NOT_LOADED,
                    message: "model not loaded".into(),
                };
            }
        };

        let start = Instant::now();

        // ── Stub mode: return canned responses immediately ──
        if is_stub {
            return self.stub_infer(mode, &prompt, send_progress);
        }

        // ── Real inference ──
        // Decide: DGS (template-guided, single-pass) vs Semantic ReAct (iterative).
        let use_dgs = prompt.system_prompt.contains("DGS TEMPLATE:");
        let use_bon = mode == InferenceMode::Strategist && prompt.cot_enabled;

        send_progress(NeocortexToDaemon::Progress {
            percent: 5,
            stage: "starting inference".into(),
        });

        let outcome = if use_bon {
            // Layer 5: Best-of-N for high-stakes tasks
            info!("using Best-of-N sampling (Layer 5)");
            self.infer_bon(manager, &prompt, mode, send_progress, start)
        } else if use_dgs {
            // DGS: single pass, template-guided
            info!("using DGS single-pass inference");
            self.infer_single_pass(manager, &prompt, mode, send_progress, start)
        } else {
            // Semantic ReAct: iterative reasoning
            info!("using Semantic ReAct iterative inference");
            self.infer_with_cascade(manager, &prompt, mode, send_progress, start)
        };

        let outcome = match outcome {
            Ok(o) => o,
            Err(resp) => return resp,
        };

        // Record confidence on the loaded model
        if let Some(m) = manager.loaded_mut() {
            m.record_inference(outcome.confidence);
        }

        // Layer 4: Reflection for structured modes (Planner/Strategist)
        let outcome = if matches!(mode, InferenceMode::Planner | InferenceMode::Strategist)
            && outcome.confidence >= LOW_CONFIDENCE_THRESHOLD
        {
            self.maybe_reflect(manager, outcome, mode, &prompt, send_progress)
        } else {
            outcome
        };

        // Convert to IPC response
        convert_outcome_to_ipc(outcome, mode)
    }

    // ── Single-pass inference ───────────────────────────────────────────

    /// Run a single inference pass (DGS mode or simple generation).
    ///
    /// No iteration, no ReAct loop. Just generate, parse, and return.
    fn infer_single_pass(
        &self,
        manager: &mut ModelManager,
        prompt: &AssembledPrompt,
        mode: InferenceMode,
        send_progress: &mut ProgressSender,
        start: Instant,
    ) -> Result<InferenceOutcome, NeocortexToDaemon> {
        let gen_result = self.generate_tokens(manager, prompt, send_progress)?;

        if gen_result.was_cancelled {
            return Err(NeocortexToDaemon::Error {
                code: error_codes::CANCELLED,
                message: format!("cancelled after {} tokens", gen_result.token_count),
            });
        }

        let raw_output = gen_result.text.clone();

        // If CoT was enabled, unwrap the thinking wrapper
        let (effective_output, cot_thinking) = if prompt.cot_enabled {
            unwrap_cot_output(&raw_output)
        } else {
            (raw_output.clone(), None)
        };

        // Parse output
        let parsed = match tool_format::parse_for_mode(mode, &effective_output) {
            Ok(p) => Some(p),
            Err(e) => {
                warn!(error = %e, "output parsing failed, will return raw");
                None
            }
        };

        // Estimate confidence
        let confidence = estimate_confidence_from_output(
            &effective_output,
            mode,
            gen_result.mean_logprob,
            gen_result.stopped_by_sequence,
        );

        let elapsed = start.elapsed().as_millis() as u64;
        info!(
            tokens = gen_result.token_count,
            confidence,
            elapsed_ms = elapsed,
            "single-pass inference complete"
        );

        Ok(InferenceOutcome {
            raw_output,
            parsed,
            confidence,
            tokens_generated: gen_result.token_count,
            cot_thinking,
        })
    }

    // ── Cascade-wrapped inference ───────────────────────────────────────

    /// Run inference with cascade retry (Layer 3).
    ///
    /// Starts with the current model tier. If confidence is too low and
    /// a larger model is available, escalates and retries.
    fn infer_with_cascade(
        &self,
        manager: &mut ModelManager,
        prompt: &AssembledPrompt,
        mode: InferenceMode,
        send_progress: &mut ProgressSender,
        start: Instant,
    ) -> Result<InferenceOutcome, NeocortexToDaemon> {
        manager.reset_cascades();
        let mut last_outcome: Option<InferenceOutcome> = None;

        loop {
            // Run inference (ReAct or single-pass based on mode)
            let outcome = if matches!(mode, InferenceMode::Planner | InferenceMode::Strategist) {
                self.infer_react_loop(manager, prompt, mode, send_progress, start)?
            } else {
                self.infer_single_pass(manager, prompt, mode, send_progress, start)?
            };

            // Check confidence
            if outcome.confidence >= CASCADE_CONFIDENCE_THRESHOLD {
                info!(
                    confidence = outcome.confidence,
                    "confidence above threshold, accepting output"
                );
                return Ok(outcome);
            }

            // Low confidence — try cascade
            let current_tier = manager
                .current_tier()
                .unwrap_or(aura_types::ipc::ModelTier::Brainstem1_5B);

            if manager.cascades_exhausted() {
                warn!(
                    confidence = outcome.confidence,
                    "cascade retries exhausted, accepting low-confidence output"
                );
                // Return best outcome we have
                return Ok(match last_outcome {
                    Some(prev) if prev.confidence > outcome.confidence => prev,
                    _ => outcome,
                });
            }

            // Check if we can escalate
            let available_mb = model::available_ram_mb();
            let power = model::PowerState::Normal; // conservative default during inference
            let should_up =
                model::should_cascade_up(current_tier, outcome.confidence, available_mb, power);

            if should_up.is_none() {
                debug!(
                    confidence = outcome.confidence,
                    "cascade not recommended, accepting output"
                );
                return Ok(outcome);
            }

            // Attempt cascade escalation
            let next_tier = match model::tier_upgrade(current_tier) {
                Some(t) => t,
                None => {
                    debug!("already at highest tier, accepting output");
                    return Ok(outcome);
                }
            };

            send_progress(NeocortexToDaemon::Progress {
                percent: 30,
                stage: format!(
                    "escalating to {} (confidence {:.0}%)",
                    model::tier_display(next_tier),
                    outcome.confidence * 100.0,
                ),
            });

            let params = ModelParams {
                model_tier: next_tier,
                ..ModelParams::default()
            };

            match manager.cascade_to(next_tier, &params) {
                Ok((name, mem)) => {
                    info!(
                        model = name,
                        memory_mb = mem,
                        "cascade escalation successful"
                    );
                    last_outcome = Some(outcome);
                    // Loop again with the new model
                }
                Err(e) => {
                    warn!(error = %e, "cascade escalation failed, accepting current output");
                    return Ok(outcome);
                }
            }
        }
    }

    // ── ReAct iterative reasoning ───────────────────────────────────────

    /// Run a ReAct Thought→Action→Observation loop.
    ///
    /// Each iteration:
    /// 1. Build prompt with accumulated ReAct history
    /// 2. Generate tokens
    /// 3. Parse the Thought and Action from output
    /// 4. Check for DONE marker (final answer)
    /// 5. If not done, create an Observation (simulated or from tool exec)
    /// 6. Append step and repeat
    fn infer_react_loop(
        &self,
        manager: &mut ModelManager,
        base_prompt: &AssembledPrompt,
        mode: InferenceMode,
        send_progress: &mut ProgressSender,
        start: Instant,
    ) -> Result<InferenceOutcome, NeocortexToDaemon> {
        let mut react_state = ReActState::default();
        let mut token_tracker =
            TokenTracker::new(base_prompt.config.max_tokens.saturating_mul(2), 0.5);

        loop {
            react_state.iteration += 1;

            if self.is_cancelled() {
                return Err(NeocortexToDaemon::Error {
                    code: error_codes::CANCELLED,
                    message: "cancelled during ReAct loop".into(),
                });
            }

            if react_state.is_exhausted() {
                info!(
                    iterations = react_state.iteration,
                    "ReAct loop exhausted max iterations"
                );
                break;
            }

            if token_tracker.is_exhausted() {
                info!(
                    consumed = token_tracker.consumed(),
                    "token budget exhausted during ReAct loop"
                );
                break;
            }

            // Build ReAct prompt with history
            let slots = PromptSlots {
                goal: base_prompt.system_prompt.clone(),
                react_history: react_state.as_prompt_history(),
                grammar_kind: base_prompt.grammar_kind,
                force_cot: base_prompt.cot_enabled,
                ..Default::default()
            };

            let (react_prompt_text, react_config) = prompts::build_react_prompt(mode, &slots);

            let react_prompt = AssembledPrompt {
                system_prompt: react_prompt_text,
                config: react_config,
                estimated_tokens: prompts::estimate_tokens(&slots.goal) + react_state.total_tokens,
                was_truncated: base_prompt.was_truncated,
                grammar_kind: base_prompt.grammar_kind,
                cot_enabled: base_prompt.cot_enabled,
            };

            send_progress(NeocortexToDaemon::Progress {
                percent: ((react_state.iteration as f32 / MAX_REACT_ITERATIONS as f32) * 80.0)
                    as u8
                    + 10,
                stage: format!(
                    "reasoning step {}/{}",
                    react_state.iteration, MAX_REACT_ITERATIONS
                ),
            });

            // Generate
            let gen_result = self.generate_tokens(manager, &react_prompt, send_progress)?;
            token_tracker.record_usage(gen_result.token_count);

            if gen_result.was_cancelled {
                return Err(NeocortexToDaemon::Error {
                    code: error_codes::CANCELLED,
                    message: format!("cancelled during ReAct iteration {}", react_state.iteration),
                });
            }

            // Parse the Thought and Action from the output
            let (thought, action) = parse_react_output(&gen_result.text);

            let step = ReActStep {
                thought,
                action: action.clone(),
                observation: None, // Will be filled if we continue
            };

            // Check for DONE
            if action.contains(REACT_DONE_MARKER) {
                react_state.push_step(step);
                info!(
                    iterations = react_state.iteration,
                    "ReAct loop completed with DONE marker"
                );
                break;
            }

            // Detect mid-stream tool call
            let tool_call_detected = detect_tool_call(&action);

            // Create observation (simulated — real tool execution is in the daemon)
            let observation = if tool_call_detected {
                // In real usage, the daemon would execute the tool and return the result.
                // Here we note that a tool call was detected for the daemon to handle.
                format!(
                    "[Tool call detected: {}. Awaiting daemon execution.]",
                    action.trim()
                )
            } else {
                "[No actionable tool call found. Continue reasoning.]".to_string()
            };

            let mut completed_step = step;
            completed_step.observation = Some(observation);
            react_state.push_step(completed_step);

            // If tool call was detected, break so the daemon can execute it
            // and re-invoke with the observation
            if tool_call_detected {
                info!(
                    iteration = react_state.iteration,
                    "tool call detected, yielding to daemon for execution"
                );
                break;
            }
        }

        // Produce final outcome from the ReAct state
        let final_text = react_state.final_answer().unwrap_or_else(|| {
            // If no DONE marker, use the last action as the output
            react_state
                .steps
                .last()
                .map(|s| s.action.clone())
                .unwrap_or_default()
        });

        let (effective_output, cot_thinking) = if base_prompt.cot_enabled {
            unwrap_cot_output(&final_text)
        } else {
            (final_text.clone(), None)
        };

        let parsed = match tool_format::parse_for_mode(mode, &effective_output) {
            Ok(p) => Some(p),
            Err(e) => {
                warn!(error = %e, "ReAct final output parsing failed");
                None
            }
        };

        let confidence = estimate_confidence_from_output(&effective_output, mode, None, false);

        let elapsed = start.elapsed().as_millis() as u64;
        info!(
            iterations = react_state.iteration,
            total_tokens = react_state.total_tokens,
            confidence,
            elapsed_ms = elapsed,
            "ReAct loop complete"
        );

        Ok(InferenceOutcome {
            raw_output: final_text,
            parsed,
            confidence,
            tokens_generated: react_state.total_tokens,
            cot_thinking,
        })
    }

    // ── Best-of-N sampling (Layer 5) ────────────────────────────────────

    /// Run N inference passes with Mirostat-divergent configurations and vote
    /// on the best output.
    ///
    /// Each sample uses a different Mirostat tau (3.0, 5.0, 7.0) to produce
    /// diverse reasoning paths, not just temperature noise.
    fn infer_bon(
        &self,
        manager: &mut ModelManager,
        base_prompt: &AssembledPrompt,
        mode: InferenceMode,
        send_progress: &mut ProgressSender,
        start: Instant,
    ) -> Result<InferenceOutcome, NeocortexToDaemon> {
        let mut outcomes: Vec<InferenceOutcome> = Vec::with_capacity(BON_SAMPLES);
        let slots = PromptSlots {
            goal: base_prompt.system_prompt.clone(),
            grammar_kind: base_prompt.grammar_kind,
            force_cot: base_prompt.cot_enabled,
            ..Default::default()
        };

        for i in 0..BON_SAMPLES {
            if self.is_cancelled() {
                break;
            }

            send_progress(NeocortexToDaemon::Progress {
                percent: ((i as f32 / BON_SAMPLES as f32) * 60.0) as u8 + 10,
                stage: format!("BoN sample {}/{}", i + 1, BON_SAMPLES),
            });

            let (bon_prompt_text, bon_config) = prompts::build_bon_prompt(mode, &slots, i);

            let bon_prompt = AssembledPrompt {
                system_prompt: bon_prompt_text,
                config: bon_config,
                estimated_tokens: base_prompt.estimated_tokens,
                was_truncated: base_prompt.was_truncated,
                grammar_kind: base_prompt.grammar_kind,
                cot_enabled: base_prompt.cot_enabled,
            };

            let gen_result = match self.generate_tokens(manager, &bon_prompt, send_progress) {
                Ok(r) => r,
                Err(_err) => {
                    warn!(sample = i, "BoN sample failed, skipping");
                    continue;
                }
            };

            if gen_result.was_cancelled {
                break;
            }

            let (effective_output, cot_thinking) = if base_prompt.cot_enabled {
                unwrap_cot_output(&gen_result.text)
            } else {
                (gen_result.text.clone(), None)
            };

            let parsed = tool_format::parse_for_mode(mode, &effective_output).ok();

            let confidence = estimate_confidence_from_output(
                &effective_output,
                mode,
                gen_result.mean_logprob,
                gen_result.stopped_by_sequence,
            );

            outcomes.push(InferenceOutcome {
                raw_output: gen_result.text,
                parsed,
                confidence,
                tokens_generated: gen_result.token_count,
                cot_thinking,
            });
        }

        if outcomes.is_empty() {
            return Err(NeocortexToDaemon::Error {
                code: error_codes::GENERATION_FAILED,
                message: "all BoN samples failed or were cancelled".into(),
            });
        }

        // Vote: pick the outcome with the highest confidence
        let best_idx = outcomes
            .iter()
            .enumerate()
            .max_by(|(_, a), (_, b)| {
                a.confidence
                    .partial_cmp(&b.confidence)
                    .unwrap_or(std::cmp::Ordering::Equal)
            })
            .map(|(i, _)| i)
            .unwrap_or(0);

        let elapsed = start.elapsed().as_millis() as u64;
        info!(
            samples = outcomes.len(),
            best_confidence = outcomes[best_idx].confidence,
            elapsed_ms = elapsed,
            "BoN voting complete, selected sample {}",
            best_idx
        );

        // Remove and return the best
        Ok(outcomes.swap_remove(best_idx))
    }

    // ── Reflection (Layer 4) ────────────────────────────────────────────

    /// Optionally run reflection using the Brainstem model.
    ///
    /// If the Brainstem rejects the output, we return the output anyway
    /// but with reduced confidence and a warning logged.
    /// (Full reflection with re-inference on rejection is deferred to when
    /// the Brainstem model can be loaded in parallel.)
    fn maybe_reflect(
        &self,
        _manager: &mut ModelManager,
        mut outcome: InferenceOutcome,
        _mode: InferenceMode,
        _prompt: &AssembledPrompt,
        _send_progress: &mut ProgressSender,
    ) -> InferenceOutcome {
        // TODO: When multi-model loading is supported, load Brainstem in
        // parallel and run reflection. For now, we do a heuristic check.

        // Heuristic reflection: check structural validity
        let grammar_valid = outcome
            .parsed
            .as_ref()
            .map(|p| match p {
                ParsedOutput::Plan(plan) => {
                    !plan.steps.is_empty() && !plan.goal_description.is_empty()
                }
                ParsedOutput::Steps(steps) => !steps.is_empty(),
                ParsedOutput::Reply(text) => !text.is_empty(),
            })
            .unwrap_or(false);

        if !grammar_valid {
            warn!(
                original_confidence = outcome.confidence,
                "heuristic reflection: output failed structural check"
            );
            outcome.confidence *= 0.7; // Penalty
        } else {
            trace!("heuristic reflection: output passed structural check");
        }

        outcome
    }

    // ── Token generation (core loop) ────────────────────────────────────

    /// Generate tokens from the model using the llama backend.
    ///
    /// Handles:
    /// - Tokenization via the backend (real on Android, bigram stub on host)
    /// - Prompt evaluation (feeding tokens into the model)
    /// - Token-by-token generation loop with EOS detection
    /// - Sampling with temperature, top_p, top_k, repetition penalty
    /// - Stop sequence detection
    /// - Cancellation checks
    /// - Progress reporting
    /// - Decoding tokens back to text
    fn generate_tokens(
        &self,
        manager: &mut ModelManager,
        prompt: &AssembledPrompt,
        send_progress: &mut ProgressSender,
    ) -> Result<GenerationResult, NeocortexToDaemon> {
        let loaded = match manager.loaded() {
            Some(m) => m,
            None => {
                return Err(NeocortexToDaemon::Error {
                    code: error_codes::MODEL_NOT_LOADED,
                    message: "model not loaded during token generation".into(),
                });
            }
        };

        let backend = aura_llama_sys::backend();

        // Tokenize the full prompt (system + user content)
        let prompt_tokens = backend
            .tokenize(loaded.ctx_ptr, &prompt.system_prompt)
            .map_err(|e| {
                error!(error = %e, "tokenization failed");
                NeocortexToDaemon::Error {
                    code: error_codes::GENERATION_FAILED,
                    message: format!("tokenization failed: {}", e),
                }
            })?;

        debug!(
            prompt_tokens = prompt_tokens.len(),
            stub = backend.is_stub(),
            "prompt tokenized"
        );

        // Evaluate/ingest the prompt tokens
        backend.eval(loaded.ctx_ptr, &prompt_tokens).map_err(|e| {
            error!(error = %e, "prompt evaluation failed");
            NeocortexToDaemon::Error {
                code: error_codes::GENERATION_FAILED,
                message: format!("prompt eval failed: {}", e),
            }
        })?;

        // Build sampling parameters from prompt config
        let sampling_params = aura_llama_sys::SamplingParams {
            temperature: prompt.config.temperature,
            top_p: prompt.config.top_p,
            top_k: prompt.config.top_k,
            repeat_penalty: prompt.config.repeat_penalty,
            max_tokens: prompt.config.max_tokens,
        };

        let eos_token = backend.eos_token();
        let max_tokens = prompt.config.max_tokens;
        let mut all_tokens: Vec<aura_llama_sys::LlamaToken> = prompt_tokens;
        let mut generated_tokens: Vec<aura_llama_sys::LlamaToken> = Vec::new();
        let mut last_progress = Instant::now();
        let mut token_count = 0u32;
        let mut stopped_by_sequence = false;

        // Token generation loop
        while token_count < max_tokens {
            if self.is_cancelled() {
                info!(token_count, "generation cancelled");
                let text = backend
                    .detokenize(loaded.ctx_ptr, &generated_tokens)
                    .unwrap_or_default();
                return Ok(GenerationResult {
                    text,
                    token_count,
                    stopped_by_sequence: false,
                    was_cancelled: true,
                    mean_logprob: None,
                });
            }

            // Sample next token from the model
            let next_token = backend
                .sample_next(loaded.ctx_ptr, &all_tokens, &sampling_params)
                .map_err(|e| {
                    error!(error = %e, token_count, "token sampling failed");
                    NeocortexToDaemon::Error {
                        code: error_codes::GENERATION_FAILED,
                        message: format!("token sampling failed at token {}: {}", token_count, e),
                    }
                })?;

            // EOS detection
            if next_token == eos_token {
                debug!(token_count, "EOS token received — stopping generation");
                break;
            }

            generated_tokens.push(next_token);
            all_tokens.push(next_token);
            token_count += 1;

            // Stop sequence detection (check partial decode every 10 tokens)
            if !prompt.config.stop_sequences.is_empty() && token_count % 10 == 0 {
                let partial_text = backend
                    .detokenize(loaded.ctx_ptr, &generated_tokens)
                    .unwrap_or_default();
                for &stop in prompt.config.stop_sequences {
                    if partial_text.ends_with(stop) {
                        debug!(stop_sequence = stop, "stop sequence detected");
                        stopped_by_sequence = true;
                        break;
                    }
                }
                if stopped_by_sequence {
                    break;
                }
            }

            // Progress reporting
            let elapsed_since = last_progress.elapsed().as_millis() as u64;
            if elapsed_since >= PROGRESS_INTERVAL_MS || token_count % PROGRESS_INTERVAL_TOKENS == 0
            {
                let percent = ((token_count as f32 / max_tokens as f32) * 100.0) as u8;
                send_progress(NeocortexToDaemon::Progress {
                    percent: percent.min(99),
                    stage: format!("generating ({}/{})", token_count, max_tokens),
                });
                last_progress = Instant::now();
            }
        }

        // Decode generated tokens to text
        let output_text = backend
            .detokenize(loaded.ctx_ptr, &generated_tokens)
            .unwrap_or_default();

        // Strip any trailing stop sequences from the output
        let output_text = strip_stop_sequences(&output_text, prompt.config.stop_sequences);

        info!(
            token_count,
            output_len = output_text.len(),
            stopped_by_sequence,
            stub = backend.is_stub(),
            "token generation complete"
        );

        Ok(GenerationResult {
            text: output_text,
            token_count,
            stopped_by_sequence,
            was_cancelled: false,
            mean_logprob: None, // TODO: compute from real logprobs on Android
        })
    }

    // ── Stub inference (host builds) ────────────────────────────────────

    /// Produce canned responses for host-build testing.
    ///
    /// Simulates progress, then returns mode-appropriate canned output.
    fn stub_infer(
        &self,
        mode: InferenceMode,
        _prompt: &AssembledPrompt,
        send_progress: &mut ProgressSender,
    ) -> NeocortexToDaemon {
        debug!(mode = ?mode, "running stub inference");

        // Simulate some progress.
        send_progress(NeocortexToDaemon::Progress {
            percent: 50,
            stage: "generating".into(),
        });

        match mode {
            InferenceMode::Planner | InferenceMode::Strategist => NeocortexToDaemon::PlanReady {
                plan: canned_action_plan(),
            },
            InferenceMode::Composer => NeocortexToDaemon::ComposedScript {
                steps: canned_dsl_steps(),
            },
            InferenceMode::Conversational => NeocortexToDaemon::ConversationReply {
                text: canned_conversation_reply(),
                mood_hint: Some(0.6),
            },
        }
    }
}

// ─── Helper: decode tokens ──────────────────────────────────────────────────

/// Decode a slice of tokens back to text using the loaded model's backend.
fn decode_tokens(manager: &ModelManager, tokens: &[aura_llama_sys::LlamaToken]) -> String {
    let ctx_ptr = match manager.loaded() {
        Some(m) => m.ctx_ptr,
        None => {
            error!("attempted to decode tokens without a loaded model");
            return String::new();
        }
    };

    aura_llama_sys::backend()
        .detokenize(ctx_ptr, tokens)
        .unwrap_or_else(|e| {
            error!(error = %e, "token decoding failed");
            String::new()
        })
}

// ─── Output parsing helpers ─────────────────────────────────────────────────

/// Convert an `InferenceOutcome` into the appropriate `NeocortexToDaemon` IPC message.
fn convert_outcome_to_ipc(outcome: InferenceOutcome, mode: InferenceMode) -> NeocortexToDaemon {
    // If we have a parsed output, use it directly
    if let Some(parsed) = outcome.parsed {
        return match parsed {
            ParsedOutput::Plan(plan) => NeocortexToDaemon::PlanReady { plan },
            ParsedOutput::Steps(steps) => NeocortexToDaemon::ComposedScript { steps },
            ParsedOutput::Reply(text) => NeocortexToDaemon::ConversationReply {
                text,
                mood_hint: Some(estimate_mood(&outcome.raw_output)),
            },
        };
    }

    // Fallback: parse from raw output
    match tool_format::parse_for_mode(mode, &outcome.raw_output) {
        Ok(parsed) => match parsed {
            ParsedOutput::Plan(plan) => NeocortexToDaemon::PlanReady { plan },
            ParsedOutput::Steps(steps) => NeocortexToDaemon::ComposedScript { steps },
            ParsedOutput::Reply(text) => NeocortexToDaemon::ConversationReply {
                text,
                mood_hint: Some(estimate_mood(&outcome.raw_output)),
            },
        },
        Err(e) => {
            warn!(error = %e, "final output parsing failed, returning as conversation reply");
            // Last resort: return raw text as conversation
            NeocortexToDaemon::ConversationReply {
                text: outcome.raw_output,
                mood_hint: Some(0.0),
            }
        }
    }
}

/// Extract content between `<tag>` and `</tag>`.
fn extract_tagged(text: &str, tag: &str) -> Option<String> {
    let open = format!("<{tag}>");
    let close = format!("</{tag}>");

    let start = text.find(&open)?;
    let end = text.find(&close)?;

    if end <= start {
        return None;
    }

    let content = &text[start + open.len()..end];
    Some(content.trim().to_string())
}

/// Unwrap a chain-of-thought JSON wrapper, returning (effective_output, thinking).
///
/// If the output is CoT-wrapped JSON (`{"thinking": "...", "action": ...}`),
/// extracts the action as the effective output and the thinking text.
/// Falls back to the original text if unwrapping fails.
fn unwrap_cot_output(raw: &str) -> (String, Option<String>) {
    let cot = ChainOfThoughtOutput::parse(raw);
    if !cot.thinking.is_empty() {
        debug!(thinking_len = cot.thinking.len(), "unwrapped CoT thinking");
        (cot.action, Some(cot.thinking))
    } else {
        (raw.to_string(), None)
    }
}

/// Parse a ReAct iteration output into (Thought, Action).
///
/// Expected format:
/// ```text
/// Thought: <reasoning>
/// Action: <action or DONE: <answer>>
/// ```
fn parse_react_output(text: &str) -> (String, String) {
    let mut thought = String::new();
    let mut action = String::new();
    let mut in_thought = false;
    let mut in_action = false;

    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("Thought:") {
            in_thought = true;
            in_action = false;
            thought.push_str(trimmed.trim_start_matches("Thought:").trim());
            thought.push('\n');
        } else if trimmed.starts_with("Action:") {
            in_action = true;
            in_thought = false;
            action.push_str(trimmed.trim_start_matches("Action:").trim());
            action.push('\n');
        } else if in_thought {
            thought.push_str(trimmed);
            thought.push('\n');
        } else if in_action {
            action.push_str(trimmed);
            action.push('\n');
        }
    }

    // If parsing failed completely, treat entire output as the action
    if thought.is_empty() && action.is_empty() {
        action = text.to_string();
    }

    (thought.trim().to_string(), action.trim().to_string())
}

/// Detect if an action string contains a tool call pattern.
///
/// Looks for JSON-like tool call structures or known tool names.
fn detect_tool_call(action_text: &str) -> bool {
    let trimmed = action_text.trim();

    // JSON object with "tool" or "action" fields
    if trimmed.starts_with('{')
        && trimmed.ends_with('}')
        && (trimmed.contains("\"tool\"") || trimmed.contains("\"action\""))
    {
        return true;
    }

    // Known tool call patterns
    if trimmed.starts_with("CALL:") || trimmed.starts_with("EXECUTE:") {
        return true;
    }

    // ActionType-like patterns
    if trimmed.contains("OpenApp")
        || trimmed.contains("Tap{")
        || trimmed.contains("\"Swipe\"")
        || trimmed.contains("\"TypeText\"")
    {
        return true;
    }

    false
}

/// Strip trailing stop sequences from generated text.
fn strip_stop_sequences(text: &str, stop_sequences: &[&str]) -> String {
    let mut result = text.to_string();
    for stop in stop_sequences {
        if result.ends_with(stop) {
            result.truncate(result.len() - stop.len());
        }
    }
    result.trim_end().to_string()
}

// ─── Confidence estimation ──────────────────────────────────────────────────

/// Estimate confidence from output quality signals.
///
/// Combines heuristic signals (structure, length, formatting) with
/// optional logprob data when available.
fn estimate_confidence_from_output(
    output: &str,
    mode: InferenceMode,
    mean_logprob: Option<f32>,
    stopped_naturally: bool,
) -> f32 {
    let mut confidence: f32 = 0.5; // Base

    // Logprob-based confidence (strongest signal when available)
    if let Some(lp) = mean_logprob {
        // Higher (less negative) logprobs = more confident
        // Typical range: -3.0 (very uncertain) to -0.1 (very confident)
        let lp_score = (1.0 + lp / 3.0).clamp(0.0, 1.0);
        confidence = lp_score * 0.6 + confidence * 0.4;
    }

    // Natural stop (hit stop sequence or EOS) is a good sign
    if stopped_naturally {
        confidence += 0.1;
    }

    // Mode-specific structural checks
    match mode {
        InferenceMode::Planner | InferenceMode::Strategist => {
            // Should contain JSON-like structure
            if output.contains("goal_description") && output.contains("steps") {
                confidence += 0.15;
            }
            if output.contains("action") && output.contains("target") {
                confidence += 0.05;
            }
        }
        InferenceMode::Composer => {
            // Should be a JSON array
            if output.trim().starts_with('[') && output.trim().ends_with(']') {
                confidence += 0.15;
            }
        }
        InferenceMode::Conversational => {
            // Any non-trivial text is fine
            if output.len() > 10 {
                confidence += 0.1;
            }
        }
    }

    // Length penalties
    if output.len() < 5 {
        confidence -= 0.3; // Suspiciously short
    }
    if output.len() > 10_000 {
        confidence -= 0.1; // Suspiciously long (possible runaway)
    }

    // Reasonable length bonus
    if output.len() > 20 && output.len() < 5000 {
        confidence += 0.05;
    }

    confidence.clamp(0.05, 0.99)
}

/// Estimate mood valence from reply text (simple heuristic).
fn estimate_mood(text: &str) -> f32 {
    let lower = text.to_lowercase();
    let positive = ["happy", "great", "sure", "love", "awesome", "yes", "!"];
    let negative = ["sorry", "can't", "error", "fail", "unfortunately", "no"];

    let pos_count = positive.iter().filter(|w| lower.contains(**w)).count() as f32;
    let neg_count = negative.iter().filter(|w| lower.contains(**w)).count() as f32;

    ((pos_count - neg_count) / 3.0).clamp(-1.0, 1.0)
}

// ─── Canned responses (stub mode) ──────────────────────────────────────────

/// Canned `ActionPlan` for Planner/Strategist stub responses.
fn canned_action_plan() -> ActionPlan {
    ActionPlan {
        goal_description: "Open the settings app".into(),
        steps: vec![
            DslStep {
                action: ActionType::OpenApp {
                    package: "com.android.settings".into(),
                },
                target: None,
                timeout_ms: 5000,
                on_failure: FailureStrategy::Retry { max: 3 },
                precondition: None,
                postcondition: Some(aura_types::dsl::DslCondition::AppInForeground(
                    "com.android.settings".into(),
                )),
                label: Some("Launch Settings app".into()),
            },
            DslStep {
                action: ActionType::WaitForElement {
                    selector: TargetSelector::Text("Settings".into()),
                    timeout_ms: 3000,
                },
                target: Some(TargetSelector::Text("Settings".into())),
                timeout_ms: 3000,
                on_failure: FailureStrategy::Retry { max: 2 },
                precondition: None,
                postcondition: None,
                label: Some("Wait for Settings title".into()),
            },
            DslStep {
                action: ActionType::AssertElement {
                    selector: TargetSelector::Text("Settings".into()),
                    expected: ElementAssertion::Exists,
                },
                target: Some(TargetSelector::Text("Settings".into())),
                timeout_ms: 2000,
                on_failure: FailureStrategy::AskUser("Settings screen not visible".into()),
                precondition: None,
                postcondition: None,
                label: Some("Verify Settings screen".into()),
            },
        ],
        estimated_duration_ms: 8000,
        confidence: 0.85,
        source: PlanSource::LlmGenerated,
    }
}

/// Canned `Vec<DslStep>` for Composer stub responses.
fn canned_dsl_steps() -> Vec<DslStep> {
    vec![
        DslStep {
            action: ActionType::Tap { x: 540, y: 960 },
            target: Some(TargetSelector::ResourceId("settings_button".into())),
            timeout_ms: 3000,
            on_failure: FailureStrategy::Retry { max: 3 },
            precondition: None,
            postcondition: None,
            label: Some("Tap settings button".into()),
        },
        DslStep {
            action: ActionType::WaitForElement {
                selector: TargetSelector::Text("General".into()),
                timeout_ms: 2000,
            },
            target: Some(TargetSelector::Text("General".into())),
            timeout_ms: 2000,
            on_failure: FailureStrategy::Skip,
            precondition: None,
            postcondition: None,
            label: Some("Wait for settings page".into()),
        },
    ]
}

/// Canned reply text for Conversational stub responses.
fn canned_conversation_reply() -> String {
    "Hey! I'm here and ready to help. What would you like me to do on your phone?".into()
}

// ─── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Helper: build test engine ────────────────────────────────────

    fn test_engine() -> (InferenceEngine, Arc<AtomicBool>) {
        let cancel = Arc::new(AtomicBool::new(false));
        let engine = InferenceEngine::new(cancel.clone());
        (engine, cancel)
    }

    fn test_prompt(mode: InferenceMode) -> AssembledPrompt {
        AssembledPrompt {
            system_prompt: "test prompt".into(),
            config: prompts::mode_config(mode),
            estimated_tokens: 100,
            was_truncated: false,
            grammar_kind: None,
            cot_enabled: false,
        }
    }

    fn noop_sender() -> ProgressSender {
        Box::new(|_| {})
    }

    fn collecting_sender() -> (
        ProgressSender,
        Arc<std::sync::Mutex<Vec<NeocortexToDaemon>>>,
    ) {
        let messages = Arc::new(std::sync::Mutex::new(Vec::new()));
        let clone = Arc::clone(&messages);
        let sender: ProgressSender = Box::new(move |msg| {
            clone.lock().expect("test lock poisoned").push(msg);
        });
        (sender, messages)
    }

    // ── extract_tagged ──────────────────────────────────────────────

    #[test]
    fn extract_tagged_content() {
        let text = "Some preamble <plan>step1\nstep2</plan> some epilogue";
        assert_eq!(extract_tagged(text, "plan"), Some("step1\nstep2".into()));
    }

    #[test]
    fn extract_tagged_missing_returns_none() {
        assert_eq!(extract_tagged("no tags here", "plan"), None);
    }

    #[test]
    fn extract_tagged_nested() {
        let text = "<reply>Hello there!</reply><action>{\"type\":\"Tap\"}</action>";
        assert_eq!(extract_tagged(text, "reply"), Some("Hello there!".into()));
        assert_eq!(
            extract_tagged(text, "action"),
            Some("{\"type\":\"Tap\"}".into())
        );
    }

    // ── Confidence estimation ───────────────────────────────────────

    #[test]
    fn confidence_good_structured_output() {
        let good = r#"{"goal_description": "open settings", "steps": [{"action": "Tap", "target": "btn"}]}"#;
        let conf = estimate_confidence_from_output(good, InferenceMode::Planner, None, true);
        assert!(conf >= 0.7, "expected >= 0.7, got {conf}");
    }

    #[test]
    fn confidence_very_short_output() {
        let short = "ok";
        let conf = estimate_confidence_from_output(short, InferenceMode::Planner, None, false);
        assert!(conf < 0.5, "expected < 0.5, got {conf}");
    }

    #[test]
    fn confidence_empty_output() {
        let conf = estimate_confidence_from_output("", InferenceMode::Conversational, None, false);
        assert!(conf < 0.3, "expected < 0.3, got {conf}");
    }

    #[test]
    fn confidence_with_logprobs() {
        // High logprob (close to 0) = high confidence
        let conf = estimate_confidence_from_output(
            "Some reasonable output text",
            InferenceMode::Conversational,
            Some(-0.5),
            true,
        );
        assert!(conf > 0.6, "expected > 0.6, got {conf}");

        // Low logprob (very negative) = low confidence
        let conf = estimate_confidence_from_output(
            "Some output",
            InferenceMode::Conversational,
            Some(-3.0),
            false,
        );
        assert!(conf < 0.5, "expected < 0.5, got {conf}");
    }

    #[test]
    fn confidence_composer_json_array() {
        let array = r#"[{"action": "Tap", "x": 100}]"#;
        let conf = estimate_confidence_from_output(array, InferenceMode::Composer, None, true);
        assert!(conf > 0.6, "expected > 0.6, got {conf}");
    }

    // ── Mood estimation ─────────────────────────────────────────────

    #[test]
    fn mood_estimation_positive() {
        let mood = estimate_mood("Sure, I'd love to help! That's awesome!");
        assert!(mood > 0.0);
    }

    #[test]
    fn mood_estimation_negative() {
        let mood = estimate_mood("Sorry, I can't do that unfortunately.");
        assert!(mood < 0.0);
    }

    #[test]
    fn mood_estimation_neutral() {
        let mood = estimate_mood("The weather is mild today.");
        assert!(mood.abs() < 0.5);
    }

    // ── Canned responses ────────────────────────────────────────────

    #[test]
    fn canned_responses_are_valid() {
        let plan = canned_action_plan();
        assert!(!plan.steps.is_empty());
        assert_eq!(plan.source, PlanSource::LlmGenerated);
        assert!(plan.confidence > 0.0);
        assert!(!plan.goal_description.is_empty());

        let steps = canned_dsl_steps();
        assert!(!steps.is_empty());

        let reply = canned_conversation_reply();
        assert!(!reply.is_empty());
    }

    // ── Stub inference ──────────────────────────────────────────────

    #[test]
    fn stub_infer_produces_plan_for_planner() {
        let (engine, _) = test_engine();
        let prompt = test_prompt(InferenceMode::Planner);
        let (mut sender, messages) = collecting_sender();

        let result = engine.stub_infer(InferenceMode::Planner, &prompt, &mut sender);

        match result {
            NeocortexToDaemon::PlanReady { plan } => {
                assert!(!plan.steps.is_empty());
                assert!(plan.confidence > 0.0);
            }
            other => panic!("expected PlanReady, got {other:?}"),
        }

        assert!(!messages.lock().expect("test lock poisoned").is_empty());
    }

    #[test]
    fn stub_infer_produces_script_for_composer() {
        let (engine, _) = test_engine();
        let prompt = test_prompt(InferenceMode::Composer);
        let mut sender = noop_sender();

        let result = engine.stub_infer(InferenceMode::Composer, &prompt, &mut sender);

        match result {
            NeocortexToDaemon::ComposedScript { steps } => {
                assert!(!steps.is_empty());
            }
            other => panic!("expected ComposedScript, got {other:?}"),
        }
    }

    #[test]
    fn stub_infer_produces_reply_for_conversational() {
        let (engine, _) = test_engine();
        let prompt = test_prompt(InferenceMode::Conversational);
        let mut sender = noop_sender();

        let result = engine.stub_infer(InferenceMode::Conversational, &prompt, &mut sender);

        match result {
            NeocortexToDaemon::ConversationReply { text, mood_hint } => {
                assert!(!text.is_empty());
                assert!(mood_hint.is_some());
            }
            other => panic!("expected ConversationReply, got {other:?}"),
        }
    }

    // ── Cancellation ────────────────────────────────────────────────

    #[test]
    fn cancellation_works() {
        let (engine, cancel) = test_engine();
        assert!(!engine.is_cancelled());
        engine.cancel();
        assert!(engine.is_cancelled());

        // Verify the shared token is set
        assert!(cancel.load(Ordering::SeqCst));
    }

    #[test]
    fn cancel_token_resets_on_infer() {
        let cancel = Arc::new(AtomicBool::new(true));
        let engine = InferenceEngine::new(cancel.clone());

        // The infer method resets cancel_token to false
        // We can't easily test full infer without a model, but verify
        // that cancel() and is_cancelled() work symmetrically
        assert!(engine.is_cancelled());
        cancel.store(false, Ordering::SeqCst);
        assert!(!engine.is_cancelled());
    }

    // ── ReAct parsing ───────────────────────────────────────────────

    #[test]
    fn parse_react_output_basic() {
        let text = "Thought: I need to open the settings app.\nAction: {\"tool\": \"open_app\", \"package\": \"com.android.settings\"}";
        let (thought, action) = parse_react_output(text);
        assert_eq!(thought, "I need to open the settings app.");
        assert!(action.contains("open_app"));
    }

    #[test]
    fn parse_react_output_with_done() {
        let text = "Thought: The task is complete.\nAction: DONE: {\"goal_description\": \"settings opened\", \"steps\": []}";
        let (thought, action) = parse_react_output(text);
        assert!(thought.contains("task is complete"));
        assert!(action.contains(REACT_DONE_MARKER));
    }

    #[test]
    fn parse_react_output_multiline_thought() {
        let text = "\
Thought: First, I need to check the current screen.
The user wants to open settings.
I should use the open_app action.
Action: {\"tool\": \"open_app\"}";
        let (thought, action) = parse_react_output(text);
        assert!(thought.contains("check the current screen"));
        assert!(thought.contains("open_app action"));
        assert!(action.contains("open_app"));
    }

    #[test]
    fn parse_react_output_no_markers() {
        let text = "just some random text without markers";
        let (thought, action) = parse_react_output(text);
        assert!(thought.is_empty());
        assert_eq!(action, text);
    }

    // ── ReAct state ─────────────────────────────────────────────────

    #[test]
    fn react_state_iteration_limit() {
        let mut state = ReActState::default();
        assert!(!state.is_exhausted());

        for _ in 0..MAX_REACT_ITERATIONS {
            state.iteration += 1;
        }
        assert!(state.is_exhausted());
    }

    #[test]
    fn react_state_done_detection() {
        let mut state = ReActState::default();
        assert!(!state.is_done());

        state.push_step(ReActStep {
            thought: "thinking".into(),
            action: "DONE: the final answer".into(),
            observation: None,
        });
        assert!(state.is_done());
    }

    #[test]
    fn react_state_final_answer_extraction() {
        let mut state = ReActState::default();
        assert!(state.final_answer().is_none());

        state.push_step(ReActStep {
            thought: "done".into(),
            action: "DONE: {\"goal\": \"open settings\"}".into(),
            observation: None,
        });

        let answer = state.final_answer().expect("should have answer");
        assert!(answer.contains("open settings"));
    }

    #[test]
    fn react_state_token_tracking() {
        let mut state = ReActState::default();
        assert_eq!(state.total_tokens, 0);

        state.push_step(ReActStep {
            thought: "a".repeat(100),
            action: "b".repeat(50),
            observation: Some("c".repeat(30)),
        });

        assert!(state.total_tokens > 0);
    }

    // ── Tool call detection ─────────────────────────────────────────

    #[test]
    fn detect_tool_call_json() {
        assert!(detect_tool_call(
            r#"{"tool": "open_app", "package": "com.android.settings"}"#
        ));
        assert!(detect_tool_call(r#"{"action": "Tap", "x": 100, "y": 200}"#));
    }

    #[test]
    fn detect_tool_call_prefixed() {
        assert!(detect_tool_call("CALL: open_app com.android.settings"));
        assert!(detect_tool_call("EXECUTE: tap 100 200"));
    }

    #[test]
    fn detect_tool_call_action_type_patterns() {
        assert!(detect_tool_call("OpenApp com.android.settings"));
    }

    #[test]
    fn detect_tool_call_negative() {
        assert!(!detect_tool_call("just some regular text"));
        assert!(!detect_tool_call("I think we should open the app"));
        assert!(!detect_tool_call(""));
    }

    // ── CoT unwrapping ──────────────────────────────────────────────

    #[test]
    fn unwrap_cot_output_valid_json() {
        let raw = r#"{"thinking": "step 1: analyze the screen\nstep 2: find the button", "action": "Tap the settings button"}"#;
        let (effective, thinking) = unwrap_cot_output(raw);
        assert_eq!(effective, "Tap the settings button");
        assert!(thinking.is_some());
        assert!(thinking.unwrap().contains("step 1"));
    }

    #[test]
    fn unwrap_cot_output_nested_action() {
        let raw = r#"{"thinking": "need to open app", "action": {"goal_description": "open settings", "steps": []}}"#;
        let (effective, thinking) = unwrap_cot_output(raw);
        assert!(effective.contains("goal_description"));
        assert!(thinking.is_some());
    }

    #[test]
    fn unwrap_cot_output_not_cot() {
        let raw = "Just a plain text response";
        let (effective, thinking) = unwrap_cot_output(raw);
        assert_eq!(effective, raw);
        assert!(thinking.is_none());
    }

    // ── Stop sequence stripping ─────────────────────────────────────

    #[test]
    fn strip_stop_sequences_basic() {
        let text = "some output</plan>";
        let result = strip_stop_sequences(text, &["</plan>", "[END]"]);
        assert_eq!(result, "some output");
    }

    #[test]
    fn strip_stop_sequences_no_match() {
        let text = "clean output";
        let result = strip_stop_sequences(text, &["</plan>", "[END]"]);
        assert_eq!(result, "clean output");
    }

    #[test]
    fn strip_stop_sequences_empty() {
        let result = strip_stop_sequences("text", &[]);
        assert_eq!(result, "text");
    }

    // ── Convert outcome to IPC ──────────────────────────────────────

    #[test]
    fn convert_outcome_plan() {
        let outcome = InferenceOutcome {
            raw_output: "test".into(),
            parsed: Some(ParsedOutput::Plan(canned_action_plan())),
            confidence: 0.8,
            tokens_generated: 100,
            cot_thinking: None,
        };
        let ipc = convert_outcome_to_ipc(outcome, InferenceMode::Planner);
        assert!(matches!(ipc, NeocortexToDaemon::PlanReady { .. }));
    }

    #[test]
    fn convert_outcome_steps() {
        let outcome = InferenceOutcome {
            raw_output: "test".into(),
            parsed: Some(ParsedOutput::Steps(canned_dsl_steps())),
            confidence: 0.7,
            tokens_generated: 50,
            cot_thinking: None,
        };
        let ipc = convert_outcome_to_ipc(outcome, InferenceMode::Composer);
        assert!(matches!(ipc, NeocortexToDaemon::ComposedScript { .. }));
    }

    #[test]
    fn convert_outcome_reply() {
        let outcome = InferenceOutcome {
            raw_output: "Hello there!".into(),
            parsed: Some(ParsedOutput::Reply("Hello there!".into())),
            confidence: 0.9,
            tokens_generated: 10,
            cot_thinking: None,
        };
        let ipc = convert_outcome_to_ipc(outcome, InferenceMode::Conversational);
        match ipc {
            NeocortexToDaemon::ConversationReply { text, .. } => {
                assert_eq!(text, "Hello there!");
            }
            other => panic!("expected ConversationReply, got {other:?}"),
        }
    }

    #[test]
    fn convert_outcome_fallback_to_raw() {
        let outcome = InferenceOutcome {
            raw_output: "unparseable garbage }{][".into(),
            parsed: None,
            confidence: 0.2,
            tokens_generated: 10,
            cot_thinking: None,
        };
        // When parse_for_mode fails on raw, it should still return a ConversationReply
        let ipc = convert_outcome_to_ipc(outcome, InferenceMode::Conversational);
        match ipc {
            NeocortexToDaemon::ConversationReply { text, .. } => {
                assert!(text.contains("unparseable"));
            }
            other => panic!("expected fallback ConversationReply, got {other:?}"),
        }
    }

    // ── Error codes ─────────────────────────────────────────────────

    #[test]
    fn error_codes_are_unique() {
        let codes = [
            error_codes::MODEL_NOT_LOADED,
            error_codes::CANCELLED,
            error_codes::GENERATION_FAILED,
            error_codes::PARSE_FAILED,
            error_codes::REFLECTION_REJECTED,
            error_codes::CASCADE_EXHAUSTED,
            error_codes::TOKEN_BUDGET_EXHAUSTED,
        ];
        let mut seen = std::collections::HashSet::new();
        for code in &codes {
            assert!(seen.insert(code), "duplicate error code: {code}");
        }
    }

    // ── Constants sanity ────────────────────────────────────────────

    #[test]
    fn constants_are_sane() {
        assert!(MAX_REACT_ITERATIONS >= 2);
        assert!(MAX_REACT_ITERATIONS <= 20);
        assert!(BON_SAMPLES >= 2);
        assert!(BON_SAMPLES <= 10);
        assert!(CASCADE_CONFIDENCE_THRESHOLD > 0.0);
        assert!(CASCADE_CONFIDENCE_THRESHOLD < 1.0);
        assert!(LOW_CONFIDENCE_THRESHOLD < CASCADE_CONFIDENCE_THRESHOLD);
        assert!(PROGRESS_INTERVAL_MS > 0);
        assert!(PROGRESS_INTERVAL_TOKENS > 0);
    }

    // ── GenerationResult ────────────────────────────────────────────

    #[test]
    fn generation_result_default_state() {
        let result = GenerationResult {
            text: String::new(),
            token_count: 0,
            stopped_by_sequence: false,
            was_cancelled: false,
            mean_logprob: None,
        };
        assert!(!result.was_cancelled);
        assert!(!result.stopped_by_sequence);
        assert!(result.mean_logprob.is_none());
    }

    // ── InferenceOutcome ────────────────────────────────────────────

    #[test]
    fn inference_outcome_with_cot() {
        let outcome = InferenceOutcome {
            raw_output: r#"{"thinking": "reasoning here", "action": "result"}"#.into(),
            parsed: Some(ParsedOutput::Reply("result".into())),
            confidence: 0.8,
            tokens_generated: 50,
            cot_thinking: Some("reasoning here".into()),
        };
        assert!(outcome.cot_thinking.is_some());
        assert_eq!(outcome.cot_thinking.unwrap(), "reasoning here");
    }

    // ── Integration: full infer with stub model ─────────────────────

    #[test]
    fn full_infer_returns_error_without_model() {
        let (engine, _) = test_engine();
        let mut manager = ModelManager::new(std::path::PathBuf::from("/tmp/models"));
        let prompt = test_prompt(InferenceMode::Planner);
        let mut sender = noop_sender();

        let result = engine.infer(&mut manager, prompt, InferenceMode::Planner, &mut sender);

        match result {
            NeocortexToDaemon::Error { code, .. } => {
                assert_eq!(code, error_codes::MODEL_NOT_LOADED);
            }
            other => panic!("expected Error, got {other:?}"),
        }
    }
}
